# Generated by Django 4.2.10 on 2024-02-29 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('split_equally', models.BooleanField(default=False)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to='myapp.userprofile')),
                ('recipients', models.ManyToManyField(related_name='payments_received', to='myapp.userprofile')),
            ],
        ),
    ]
